Traceback (most recent call last):
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\app.py", line 85, in cadastrar_paciente
    cur.execute("""
    ~~~~~~~~~~~^^^^
        INSERT INTO pacientes (nome, idade, cpf, sexo)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        VALUES (%s, %s, %s, %s)
        ^^^^^^^^^^^^^^^^^^^^^^^
    """, (nome, idade, cpf, sexo))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
    ~~~~~~~~~~^^^
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
    ~~~~~~~~~~~^^
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\wende\Downloads\sistema_hospitalar_heap_integrado\venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '08846027370' for key 'pacientes.cpf'")
